language: node_js
# required for now due to issues related to spectre  https://github.com/travis-ci/travis-ci/issues/9024
sudo: required
node_js:
  - "lts/*"
dist: trusty
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
before_install:
  # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
addons:
  chrome: stable
  code_climate:
    repo_token: d92f7df035e1822409982b8992389e722943ed74cd28c50295f027cbeb6f2362
after_script:
  - npm run coveralls
  - codeclimate-test-reporter < ./coverage/**/lcov.info